In [1]:
%matplotlib notebook
%matplotlib inline
import pandas as pd
import os
import csv
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#establishing path to the csv file
csvpath = os.path.join("Crimes_-_2001_to_Present-2.csv")

#creating DataFrame of csv data
crime_df = pd.read_csv(csvpath)

#printing DataFrame info
crime_df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12016034,JD193556,01/01/2020 12:00:00 AM,018XX N WINNEBAGO AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,32.0,22.0,11,1160263.0,1912391.0,2020,03/26/2020 03:45:12 PM,41.915306,-87.686639,"(41.915306069, -87.686639247)"
1,12220321,JD430436,01/01/2020 12:00:00 AM,091XX S DREXEL AVE,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,...,8.0,47.0,17,1184157.0,1844395.0,2020,12/19/2020 03:45:59 PM,41.728192,-87.600985,"(41.728192429, -87.600985433)"
2,12013828,JD191019,01/01/2020 12:00:00 AM,044XX S LAVERGNE AVE,0281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,...,22.0,56.0,02,1143770.0,1874726.0,2020,03/28/2020 03:47:02 PM,41.812274,-87.748177,"(41.81227369, -87.748176594)"
3,12019692,JD197444,01/01/2020 12:00:00 AM,032XX N LINCOLN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,47.0,6.0,11,1164983.0,1921507.0,2020,04/01/2020 03:50:17 PM,41.940222,-87.669039,"(41.940221932, -87.669039008)"
4,12036792,JD216459,01/01/2020 12:00:00 AM,072XX S WHIPPLE ST,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,RESIDENCE,False,False,...,18.0,66.0,11,1157290.0,1856526.0,2020,04/29/2020 03:53:17 PM,41.762067,-87.699077,"(41.762066981, -87.699077348)"

Find data with incomplete rows.

In [3]:
crime_df.count()

ID                      418753
Case Number             418753
Date                    418753
Block                   418753
IUCR                    418753
Primary Type            418753
Description             418753
Location Description    416704
Arrest                  418753
Domestic                418753
Beat                    418753
District                418753
Ward                    418733
Community Area          418752
FBI Code                418753
X Coordinate            411430
Y Coordinate            411430
Year                    418753
Updated On              418753
Latitude                411430
Longitude               411430
Location                411430
dtype: int64

In [6]:
#drop all rows with missing information.
crime_df = crime_df.dropna(how='any')

#confirm new list
crime_df.count()

ID                      409763
Case Number             409763
Date                    409763
Block                   409763
IUCR                    409763
Primary Type            409763
Description             409763
Location Description    409763
Arrest                  409763
Domestic                409763
Beat                    409763
District                409763
Ward                    409763
Community Area          409763
FBI Code                409763
X Coordinate            409763
Y Coordinate            409763
Year                    409763
Updated On              409763
Latitude                409763
Longitude               409763
Location                409763
dtype: int64

Number of each type of crime.

In [13]:
crime_df["Primary Type"].value_counts()

BATTERY                              81731
THEFT                                79486
CRIMINAL DAMAGE                      49541
ASSAULT                              38462
DECEPTIVE PRACTICE                   30941
OTHER OFFENSE                        26034
MOTOR VEHICLE THEFT                  20385
WEAPONS VIOLATION                    17361
ROBBERY                              15749
BURGLARY                             15317
NARCOTICS                            11358
CRIMINAL TRESPASS                     7528
OFFENSE INVOLVING CHILDREN            3629
CRIMINAL SEXUAL ASSAULT               2487
SEX OFFENSE                           1914
PUBLIC PEACE VIOLATION                1861
HOMICIDE                              1601
ARSON                                 1111
INTERFERENCE WITH PUBLIC OFFICER       968
STALKING                               552
PROSTITUTION                           370
LIQUOR LAW VIOLATION                   323
CONCEALED CARRY LICENSE VIOLATION      317
INTIMIDATION                           278
KIDNAPPING                             205
OBSCENITY                               97
CRIM SEXUAL ASSAULT                     75
GAMBLING                                38
HUMAN TRAFFICKING                       17
PUBLIC INDECENCY                        13
OTHER NARCOTIC VIOLATION                 8
NON-CRIMINAL                             5
RITUALISM                                1
Name: Primary Type, dtype: int64

Number of each type of crime.